In [4]:
import pandas as pd
import numpy as np
from joblib import load, dump
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [5]:
df = pd.read_csv('diabetic.csv')
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi   
0  Female  80.0             0              1           never  25.19  \
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [6]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
print(X)

[['Female' 80.0 0 ... 25.19 6.6 140]
 ['Female' 54.0 0 ... 27.32 6.6 80]
 ['Male' 28.0 0 ... 27.32 5.7 158]
 ...
 ['Male' 66.0 0 ... 27.83 5.7 155]
 ['Female' 24.0 0 ... 35.42 4.0 100]
 ['Female' 57.0 0 ... 22.43 6.6 90]]


In [8]:
print(y)

[0 0 0 ... 0 0 0]


In [9]:
ct_gender = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct_gender.fit_transform(X)

In [10]:
X[0]

array([1.0, 0.0, 0.0, 80.0, 0, 1, 'never', 25.19, 6.6, 140], dtype=object)

In [11]:
ct_smoker = ColumnTransformer([('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X = ct_smoker.fit_transform(X)

In [12]:
X[0]

array([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 80.0, 0, 1, 25.19,
       6.6, 140], dtype=object)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [26]:
RandomForest = RandomForestClassifier(n_estimators=500, n_jobs=-1)
RandomForest.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, n_jobs=-1)

In [28]:

y_pred = RandomForest.predict(X_test)
accuracy_score(y_test, y_pred)

0.9716

: 

In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

/home/codespace/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.96015